import React from 'react';
import Image from 'next/image';
import { MapPin, DollarSign, Clock, Star, Sparkles } from 'lucide-react';
import Link from 'next/link';
import placeholderImage from '@/asset/placeholder.jpg'

const SAMPLE_PLANS = [
  {
    id: 1,
    title: "Eternal Paris & Swiss Alps",
    location: "France & Switzerland",
    days: "7 Days",
    budget: "$1,500 - $2,000",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop",
    category: "Luxury"
  },
  {
    id: 2,
    title: "Kyoto Zen & Tokyo Lights",
    location: "Japan",
    days: "10 Days",
    budget: "$2,200 - $3,000",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop",
    category: "Cultural"
  },
  {
    id: 3,
    title: "Bali Tropical Expedition",
    location: "Indonesia",
    days: "5 Days",
    budget: "$800 - $1,200",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop",
    category: "Adventure"
  }
];

const ViewPlan = () => {
  return (
    <div className="min-h-screen bg-white pt-10 pb-20">
      {/* Background Glow */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-red-50 rounded-full blur-[120px] -z-10 opacity-60"></div>

      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        {/* Header Section */}
        <div className="mb-16">
          <h1 className="text-4xl lg:text-6xl font-black tracking-tighter text-slate-900 mb-4">
            AI Generated <br />
            <span className="text-red-600 italic">Travel Masterpieces</span>
          </h1>
          <p className="max-w-xl text-slate-500 font-medium text-lg leading-relaxed">
            Explore some of the best itineraries generated by our AI for travelers across the globe.
          </p>
        </div>


        {/* Grid Layout */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
          {SAMPLE_PLANS.map((plan) => (
            <div key={plan.id} className="group bg-white rounded-[32px] overflow-hidden border border-slate-100 shadow-sm hover:shadow-2xl hover:shadow-red-500/5 transition-all duration-500">
              {/* Image Section */}
              <div className="relative h-64 overflow-hidden">
                <Image
                  src={plan.image}
                  alt={plan.title}
                  fill
                  placeholder='blur'
                  blurDataURL={placeholderImage.src}
                  className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                />
                <div className="absolute top-4 left-4 bg-white/90 backdrop-blur-md px-4 py-1.5 rounded-full shadow-sm">
                  <span className="text-[10px] font-black uppercase tracking-widest text-red-600">{plan.category}</span>
                </div>
                <div className="absolute bottom-4 right-4 bg-slate-900/80 backdrop-blur-md px-3 py-1 rounded-lg flex items-center gap-1.5 text-white">
                  <Star size={14} className="fill-yellow-400 text-yellow-400" />
                  <span className="text-sm font-bold">{plan.rating}</span>
                </div>
              </div>

              {/* Content Section */}
              <div className="p-8">
                <div className="flex items-center gap-2 text-slate-400 text-xs font-bold uppercase tracking-widest mb-3">
                  <MapPin size={14} className="text-red-500" />
                  {plan.location}
                </div>
                <h3 className="text-2xl font-black text-slate-900 mb-6 group-hover:text-red-600 transition-colors">
                  {plan.title}
                </h3>

                <div className="grid grid-cols-2 gap-4 mb-8">
                  <div className="flex items-center gap-2 text-slate-600">
                    <div className="p-2 bg-slate-50 rounded-lg text-red-600">
                      <Clock size={16} />
                    </div>
                    <span className="text-sm font-bold">{plan.days}</span>
                  </div>
                  <div className="flex items-center gap-2 text-slate-600">
                    <div className="p-2 bg-slate-50 rounded-lg text-red-600">
                      <DollarSign size={16} />
                    </div>
                    <span className="text-sm font-bold">{plan.budget.split(' ')[0]}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* CTA Bottom */}
        <div className="mt-24 p-12 bg-slate-950 rounded-[48px] text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-red-600 rounded-full blur-[100px] opacity-20"></div>
          <h2 className="text-3xl font-black text-white mb-6 relative z-10">Didn't find what you're looking for?</h2>
          <Link
            href="/create-plan"
            className="inline-flex items-center gap-2 bg-red-600 text-white px-10 py-4 rounded-full font-black uppercase tracking-widest text-sm hover:bg-red-700 transition-all relative z-10 shadow-xl shadow-red-900/40">
            Create Your Own AI Plan
            <Sparkles size={18} />
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ViewPlan;